### ISSUE TITLE
Flashing arduino project

### ISSUE THREAD

**Issue by LenarOsx** [marcel-licence/esp32_basic_synth#103]
it says ml_status is missing in ml_chorus.cpp file, i've dowloaded your library.
Thanks!

**Comment by marcel-licence** [comment]
Will be fixed soon. Please copy the file from another project: https://github.com/marcel-licence/ml_epiano_example/blob/master/status_module.ino and put it into the project directory.

I will update the library soon

**Comment by LenarOsx** [comment]
Thank you!

**Comment by marcel-licence** [comment]
Should be fixed, I updated the project and the library recently
