### ISSUE TITLE
How to get wonderful Super / Hyper Saw sound?

### ISSUE THREAD

**Issue by Opekusha** [marcel-licence/esp32_basic_synth#4]
How to get wonderful Super / Hyper Saw sound from your code. Please tell me what needs to be added and where? I can't do it without your help.

**Comment by marcel-licence** [comment]
I've added the unison support to generate hyper/super saw sounds. Update your code and look for 
//#define USE_UNISON

This should be replaced by
#define USE_UNISON

This will activate the detune and unison sound generation.

     Have fun! =)
