### ISSUE TITLE
How to flash files with arduino ide

### ISSUE THREAD

**Issue by asttljsj** [marcel-licence/esp32_basic_synth#43]
Hello, how can I use arduino ide to burn files, and it prompts that delay-init is not defined during verification, thanks

**Comment by marcel-licence** [comment]
Hello,
google might help: [https://www.google.com/search?client=firefox-b-d&q=esp32+arduino+how+to]
Regarding your error message, please paste in a copy. At the moment I do not have any idea what went wrong.
Best regards,

**Comment by asttljsj** [comment]
[esp32_basic_synth.zip](https://github.com/marcel-licence/esp32_basic_synth/files/6620487/esp32_basic_synth.zip)
Hello, when I open it with arduino ide, it prompts that delay-init is not defined. What library files do you need for your project?

**Comment by HilmarSt** [comment]
Delay_Init() is implemented in the file simple_delay.ino , no additional libraries are needed.
Just make sure that all .ino files from the repo are in the same directory as the esp32_basic_synth.ino file.

**Comment by marcel-licence** [comment]
@HilmarSt thank you for posting the solution
