### ISSUE TITLE
After opening, esp32_basic_synth-main is displayed

### ISSUE THREAD

**Issue by asttljsj** [marcel-licence/esp32_basic_synth#75]
![1636731044(1)](https://user-images.githubusercontent.com/66319600/141492085-9e5bbaab-c472-4b46-93bd-4f708f2087f8.png)

**Comment by marcel-licence** [comment]
Please check your config.h file first. You should select an audio kit or ensure you have the correct configuration for your custom build. At the moment the BOARD_ML_V1 define is active (that requires the hardware I've created)

**Comment by marcel-licence** [comment]
I've updated the code and checked all configurations
