### ISSUE TITLE
Undeclared Filter_CalculateNone

### ISSUE THREAD

**Issue by mehrdavon** [marcel-licence/esp32_basic_synth#84]
Hello,

easySynth.ino line 345 is referencing method: "Filter_CalculateNone" that is not declared.
I checked the ML_synthtools library as it is where the regular "Filter_Calculate" is declared but the "~None" method is not present there.

Am I looking in the wrong place or is this a bug?

Thanks!

**Comment by marcel-licence** [comment]
Hello,

on short term you can just delete the call. I did some experiments and this call was only for temporary usage.
I will update the file and remove the call.

Viele Grüße
